### Get all contacts from 
localhost GET http://localhost:8888

### Get contact by id from localhost 
GET http://localhost:8888/movies/663f393a7dfa6a42740939fb

### Get all contacts from render 
GET https://cse341-p2-jvhe.onrender.com/movies

### Get contact by id from render 
GET https://cse341-p2-jvhe.onrender.com/movies/663f39687dfa6a42740939fc


